[package]
name = "dobby"
description = "A command line tool for automating common development tasks"
version = "0.1.3"
authors = ["Dylan Anthony <danthony@triaxtec.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/triaxtec/dobby"
keywords = ["jira", "git", "github", "workflow", "script"]
categories = ["command-line-utilities", "development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
base64 = "0.13.0"
color-eyre = "0.5.11"
console = "0.14.1"
dialoguer = "0.8.0"
toml = "0.5.8"
serde_json = { version = "1.0.64", features = ["preserve_order"] }
git2 = "0.13.20"
semver = "1.0.0"
toml_edit = "0.2.0"
execute = "0.2.9"
platform-dirs = "0.3.0"
git-conventional = "0.9.2"
markdown = "0.3.0"
ureq = { version = "2.1.1", features = ["json"] }
http = "0.2.4"
clap = "2.33.3"

[dev-dependencies]
tempfile = "3.2.0"
